server:
  http_listen_port: 3200
  log_level: warn

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 48h

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: fdc3-poc
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
  traces_storage:
    path: /tmp/tempo/generator/traces
  processor:
    local_blocks:
      filter_server_spans: false
    service_graphs:
      dimensions:
        - service.name
        - http.method
        - http.status_code
    span_metrics:
      dimensions:
        - service.name
        - http.method
        - http.status_code
        - http.target
      enable_target_info: true

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    wal:
      path: /tmp/tempo/wal

querier:
  frontend_worker:
    frontend_address: 127.0.0.1:9095

overrides:
  metrics_generator_processors:
    - local-blocks
    - service-graphs
    - span-metrics
