import type { AppDefinition } from '@fdc3-poc/fdc3-core';
import { StandardIntents } from '@fdc3-poc/fdc3-core';

/**
 * In-memory sample app directory used as fallback if app-directory.json is not found.
 * This is a compact fallback for development when config/app-directory.json is
 * unavailable. Dev-port apps are HTTP-first so the shell can host local or
 * cloud-served apps through the same path.
 */
export const SAMPLE_APP_DIRECTORY: AppDefinition[] = [
  {
    appId: 'customer-search',
    title: 'Customer Search',
    description: 'Search and browse customers by name, ID, or segment.',
    url: 'http://localhost:4001',
    devPort: 4001,
    icon: '🔍',
    category: 'CRM',
    initialLayout: { x: 50, y: 80, width: 480, height: 560 },
    listensForContexts: ['fdc3.contact'],
  },
  {
    appId: 'customer-profile',
    title: 'Customer Profile',
    description: 'Full customer profile including KYC, accounts, and recent activity.',
    url: 'http://localhost:4002',
    devPort: 4002,
    icon: '👤',
    category: 'CRM',
    initialLayout: { x: 560, y: 80, width: 560, height: 560 },
    listensForContexts: ['fdc3.contact'],
    intents: [
      {
        intent: StandardIntents.VIEW_CONTACT,
        contextTypes: ['fdc3.contact'],
        appId: 'customer-profile',
        displayName: 'View Customer Profile',
      },
    ],
  },
  {
    appId: 'portfolio-view',
    title: 'Portfolio View',
    description: 'Real-time portfolio positions, P&L, and allocation.',
    url: 'http://localhost:4003',
    devPort: 4003,
    icon: '📊',
    category: 'Investments',
    initialLayout: { x: 1150, y: 80, width: 560, height: 560 },
    listensForContexts: ['fdc3.contact', 'fdc3.portfolio'],
    intents: [
      {
        intent: StandardIntents.VIEW_PORTFOLIO,
        contextTypes: ['fdc3.contact'],
        appId: 'portfolio-view',
        displayName: 'View Portfolio',
      },
    ],
  },
  {
    appId: 'market-watch',
    title: 'Market Watch',
    description: 'Live instrument prices, news, and market data.',
    url: 'http://localhost:4004',
    devPort: 4004,
    icon: '📈',
    category: 'Markets',
    initialLayout: { x: 50, y: 680, width: 700, height: 460 },
    listensForContexts: ['fdc3.instrument'],
    intents: [
      {
        intent: StandardIntents.VIEW_INSTRUMENT,
        contextTypes: ['fdc3.instrument'],
        appId: 'market-watch',
        displayName: 'View in Market Watch',
      },
    ],
  },
  {
    appId: 'payment-action',
    title: 'Payment Action',
    description: 'Initiate and authorise customer payment instructions.',
    url: 'http://localhost:4005',
    devPort: 4005,
    icon: '💳',
    category: 'Payments',
    initialLayout: { x: 780, y: 680, width: 500, height: 460 },
    listensForContexts: [],
    intents: [
      {
        intent: StandardIntents.START_PAYMENT,
        contextTypes: ['com.demo.paymentRequest'],
        appId: 'payment-action',
        displayName: 'Start Payment',
      },
    ],
  },
  {
    appId: 'cloud-sample',
    title: 'Cloud App',
    description: 'Sample cloud-hosted app loaded directly from a remote URL — demonstrates embedding external web content.',
    url: 'https://example.com',
    devPort: 0,
    icon: '☁',
    category: 'Cloud',
    initialLayout: { x: 200, y: 200, width: 1100, height: 760 },
    listensForContexts: [],
  },

  // ─── FINOS FDC3 Community Apps ────────────────────────────────────────────

  {
    appId: 'fdc3-workbench',
    title: 'FDC3 Workbench',
    description: 'Official FINOS development and testing tool for FDC3 desktop agents. Broadcast contexts, raise intents, join channels — full API surface.',
    url: 'https://fdc3.finos.org/toolbox/fdc3-workbench/',
    devPort: 0,
    icon: '🧪',
    category: 'Developer',
    initialLayout: { x: 100, y: 100, width: 900, height: 700 },
    listensForContexts: ['fdc3.instrument', 'fdc3.contact', 'fdc3.portfolio', 'fdc3.order'],
    intents: [
      {
        intent: StandardIntents.VIEW_INSTRUMENT,
        contextTypes: ['fdc3.instrument'],
        appId: 'fdc3-workbench',
        displayName: 'View in Workbench',
      },
      {
        intent: StandardIntents.VIEW_CONTACT,
        contextTypes: ['fdc3.contact'],
        appId: 'fdc3-workbench',
        displayName: 'Inspect Contact',
      },
    ],
  },
  {
    appId: 'adaptable-demo',
    title: 'AdapTable',
    description: 'Low-code AG Grid extension with advanced FDC3 capabilities — raises and handles ViewInstrument, ViewChart, ViewOrders and more.',
    url: 'https://fdc3-demo.adaptabletools.com/',
    devPort: 0,
    icon: '⚡',
    category: 'Markets',
    initialLayout: { x: 100, y: 100, width: 1100, height: 720 },
    listensForContexts: ['fdc3.instrument'],
    intents: [
      {
        intent: StandardIntents.VIEW_INSTRUMENT,
        contextTypes: ['fdc3.instrument'],
        appId: 'adaptable-demo',
        displayName: 'View Instrument',
      },
      {
        intent: StandardIntents.VIEW_CHART,
        contextTypes: ['fdc3.instrument'],
        appId: 'adaptable-demo',
        displayName: 'View Chart',
      },
    ],
  },
  {
    appId: 'ticker-chart',
    title: 'Ticker Chart',
    description: 'Charting app powered by Polygon.io market data. Listens for ViewChart intent on fdc3.instrument.',
    url: 'https://apps.connectifi-interop.com/sail/tickerChart.html',
    devPort: 0,
    icon: '📉',
    category: 'Markets',
    initialLayout: { x: 100, y: 100, width: 900, height: 600 },
    listensForContexts: ['fdc3.instrument'],
    intents: [
      {
        intent: StandardIntents.VIEW_CHART,
        contextTypes: ['fdc3.instrument'],
        appId: 'ticker-chart',
        displayName: 'View Chart',
      },
    ],
  },
  {
    appId: 'tradingview-chart',
    title: 'TradingView Chart',
    description: 'Professional charting widget powered by TradingView. Responds to ViewChart on fdc3.instrument.',
    url: 'https://apps.connectifi-interop.com/sail/tradingviewChart.html',
    devPort: 0,
    icon: '🕯️',
    category: 'Markets',
    initialLayout: { x: 100, y: 100, width: 1000, height: 650 },
    listensForContexts: ['fdc3.instrument'],
    intents: [
      {
        intent: StandardIntents.VIEW_CHART,
        contextTypes: ['fdc3.instrument'],
        appId: 'tradingview-chart',
        displayName: 'Open in TradingView',
      },
    ],
  },
  {
    appId: 'ticker-grid',
    title: 'Ticker Grid',
    description: 'Instrument grid — browse companies and broadcast fdc3.instrument to connected apps.',
    url: 'https://apps.connectifi-interop.com/sail/tickerGrid.html',
    devPort: 0,
    icon: '🔲',
    category: 'Markets',
    initialLayout: { x: 100, y: 100, width: 800, height: 600 },
    listensForContexts: [],
  },
  {
    appId: 'ticker-details',
    title: 'Ticker Details',
    description: 'Detailed ticker information from Polygon.io. Listens for fdc3.instrument context.',
    url: 'https://apps.connectifi-interop.com/sail/tickerDetails.html',
    devPort: 0,
    icon: '🔎',
    category: 'Markets',
    initialLayout: { x: 100, y: 100, width: 700, height: 600 },
    listensForContexts: ['fdc3.instrument'],
    intents: [
      {
        intent: StandardIntents.VIEW_INSTRUMENT,
        contextTypes: ['fdc3.instrument'],
        appId: 'ticker-details',
        displayName: 'View Ticker Details',
      },
    ],
  },
  {
    appId: 'ticker-prev-close',
    title: 'Previous Close',
    description: 'Pricing snapshot at previous market close via Polygon.io. Responds to ViewQuote.',
    url: 'https://apps.connectifi-interop.com/sail/tickerPrevClose.html',
    devPort: 0,
    icon: '🔔',
    category: 'Markets',
    initialLayout: { x: 100, y: 100, width: 700, height: 500 },
    listensForContexts: ['fdc3.instrument'],
    intents: [
      {
        intent: StandardIntents.VIEW_QUOTE,
        contextTypes: ['fdc3.instrument'],
        appId: 'ticker-prev-close',
        displayName: 'View Previous Close',
      },
    ],
  },
  {
    appId: 'news-api',
    title: 'News Feed',
    description: 'Financial news search powered by NewsAPI. Listens for ViewNews on fdc3.instrument.',
    url: 'https://apps.connectifi-interop.com/sail/newsAPI.html',
    devPort: 0,
    icon: '📰',
    category: 'Markets',
    initialLayout: { x: 100, y: 100, width: 800, height: 650 },
    listensForContexts: ['fdc3.instrument'],
    intents: [
      {
        intent: StandardIntents.VIEW_NEWS,
        contextTypes: ['fdc3.instrument'],
        appId: 'news-api',
        displayName: 'View News',
      },
    ],
  },
  {
    appId: 'symphony',
    title: 'Symphony',
    description: 'Secure financial messaging platform. Handles StartChat, SendChatMessage and raises ViewContact, ViewInstrument.',
    url: 'https://develop2.symphony.com',
    devPort: 0,
    icon: '💬',
    category: 'Collaboration',
    initialLayout: { x: 100, y: 100, width: 900, height: 700 },
    listensForContexts: ['fdc3.contact'],
    intents: [
      {
        intent: StandardIntents.START_CHAT,
        contextTypes: ['fdc3.contact'],
        appId: 'symphony',
        displayName: 'Start Chat in Symphony',
      },
      {
        intent: StandardIntents.VIEW_CONTACT,
        contextTypes: ['fdc3.contact'],
        appId: 'symphony',
        displayName: 'View Contact',
      },
    ],
  },
  {
    appId: 'fdc3-explained',
    title: 'FDC3 Explained',
    description: 'Interactive learning tool for FDC3 concepts — great for onboarding new developers without writing code.',
    url: 'https://fdc3.finos.org/toolbox/fdc3-explained/1.2/',
    devPort: 0,
    icon: '📚',
    category: 'Developer',
    initialLayout: { x: 100, y: 100, width: 1000, height: 700 },
    listensForContexts: [],
  },
];
